name: spacex_demo
description: A Flutter app that demonstrates how to build a simple app using the
  SpaceX API created by the Very Good Ventures Team.
version: 1.0.0+1
homepage: https://github.com/jeroen-meijer/spacex_demo
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rocket_repository:
    path: packages/rocket_repository
  spacex_api:
    path: packages/spacex_api
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mock_navigator:
    git:
      url: https://github.com/jeroen-meijer/mock_navigator
      ref: 66086ffedfca1a56baa1670e970dfe3b94bd6848
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  network_image_mock: ^2.0.0
  plugin_platform_interface: ^2.0.0
  url_launcher_platform_interface: ^2.0.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
