name: spacex_demo
description: A Flutter app that demonstrates how to build a simple app using the
  SpaceX API created by the Very Good Ventures Team.
version: 1.0.0+1
homepage: https://github.com/VGVentures/spacex_demo
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rocket_repository:
    path: packages/rocket_repository
  spacex_api:
    path: packages/spacex_api
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mock_navigator:
    git:
      url: https://github.com/jeroen-meijer/mock_navigator
      ref: 66086ffedfca1a56baa1670e970dfe3b94bd6848
  mocktail: ^0.1.4
  plugin_platform_interface: ^2.0.1
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
