name: spacex_demo
description: A Flutter app that demonstrates how to build a simple app using the
  SpaceX API created by the Very Good Ventures Team.
version: 1.0.0+1
homepage: https://github.com/VGVentures/spacex_demo
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  crew_member_repository:
    path: packages/crew_member_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  rocket_repository:
    path: packages/rocket_repository
  spacex_api:
    path: packages/spacex_api
  url_launcher: ^6.1.12

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.5
  url_launcher_platform_interface: ^2.1.3
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
