name: spacex_demo
description: A Flutter app that demonstrates how to build a simple app using the
  SpaceX API created by the Very Good Ventures Team.
version: 1.0.0+1
homepage: https://github.com/VGVentures/spacex_demo
publish_to: none

environment:
  sdk: ">=2.14.0-0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  crew_member_repository:
    path: packages/crew_member_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rocket_repository:
    path: packages/rocket_repository
  spacex_api:
    path: packages/spacex_api
  url_launcher: ^6.0.0-nullsafety.6

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.2
  url_launcher_platform_interface: ^2.0.5
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
