name: spacex_demo
description: A Flutter app that demonstrates how to build a simple app using the
  SpaceX API created by the Very Good Ventures Team.
version: 1.0.0+1
homepage: https://github.com/VGVentures/spacex_demo
publish_to: none

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rocket_repository:
    path: packages/rocket_repository
  crew_member_repository:
    path: packages/crew_member_repository
  spacex_api:
    path: packages/spacex_api
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  intl: ^0.17.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockingjay: ^0.1.1
  bloc_test: ^8.2.0
  mocktail_image_network: ^0.1.0
  plugin_platform_interface: ^2.0.0
  url_launcher_platform_interface: ^2.0.0
  very_good_analysis: ^2.0.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
