name: spacex_api_example
description: A small example package showcasing the spacex_api.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  spacex_api:
    path: ../

dev_dependencies:
  very_good_analysis: ^5.0.0+1
