name: spacex_api
description: A Dart API Client for the unofficial SpaceX API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  http: ^0.13.3
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  json_serializable: ^4.1.3
  meta: ^1.4.0
  mocktail: ^0.1.4
  test: ^1.17.5
  very_good_analysis: ^2.1.1
