name: spacex_api
description: A Dart API Client for the unofficial SpaceX API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.6.3
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
