name: spacex_api
description: A Dart API Client for the unofficial SpaceX API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  http: ^0.13.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
