name: launch_repository
description: A Dart package to manage the launches
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  coverage: ^1.0.2
  mocktail: ^0.1.1
  test: ^1.19.2
  very_good_analysis: ^2.4.0
