name: rocket_repository
description: A Dart package for the rocket domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  coverage: ^1.0.3
  mocktail: ^0.1.4
  test: ^1.17.12
  very_good_analysis: ^2.3.0
