name: rocket_repository_example
description: A small example package showcasing the rocket_repository.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  rocket_repository:
    path: ../

dev_dependencies:
  very_good_analysis: ^2.3.0
